#!/bin/bash
mkdir -p data/redis/data
mv docker-compose.yaml docker-compose-original.yaml
mv docker-compose-actual.yaml docker-compose.yaml
docker-compose build && docker-compose up
mv docker-compose.yaml docker-compose-actual.yaml
mv docker-compose-original.yaml docker-compose.yaml
rm -rf data
